In [1]:
# Run this once if not installed
# !pip install nltk scikit-learn

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [2]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to C:\Users\Shambhu
[nltk_data]     Barangule\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Shambhu
[nltk_data]     Barangule\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Shambhu
[nltk_data]     Barangule\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to C:\Users\Shambhu
[nltk_data]     Barangule\AppData\Roaming\nltk_data...


True

In [3]:
text = """Natural Language Processing (NLP) is a field of Artificial Intelligence.
It helps computers understand, interpret and manipulate human language."""
print(text)

Natural Language Processing (NLP) is a field of Artificial Intelligence.
It helps computers understand, interpret and manipulate human language.


In [4]:
tokens = word_tokenize(text)
print(tokens)

['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'is', 'a', 'field', 'of', 'Artificial', 'Intelligence', '.', 'It', 'helps', 'computers', 'understand', ',', 'interpret', 'and', 'manipulate', 'human', 'language', '.']


In [5]:
pos_tags = pos_tag(tokens)
print(pos_tags)

[('Natural', 'JJ'), ('Language', 'NNP'), ('Processing', 'NNP'), ('(', '('), ('NLP', 'NNP'), (')', ')'), ('is', 'VBZ'), ('a', 'DT'), ('field', 'NN'), ('of', 'IN'), ('Artificial', 'JJ'), ('Intelligence', 'NNP'), ('.', '.'), ('It', 'PRP'), ('helps', 'VBZ'), ('computers', 'NNS'), ('understand', 'VBP'), (',', ','), ('interpret', 'JJ'), ('and', 'CC'), ('manipulate', 'JJ'), ('human', 'JJ'), ('language', 'NN'), ('.', '.')]


In [6]:
stop_words = set(stopwords.words('english'))

filtered_tokens = [word for word in tokens if word.lower() not in stop_words]
print(filtered_tokens)

['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'field', 'Artificial', 'Intelligence', '.', 'helps', 'computers', 'understand', ',', 'interpret', 'manipulate', 'human', 'language', '.']


In [7]:
stemmer = PorterStemmer()
stemmed = [stemmer.stem(word) for word in filtered_tokens]
print(stemmed)

['natur', 'languag', 'process', '(', 'nlp', ')', 'field', 'artifici', 'intellig', '.', 'help', 'comput', 'understand', ',', 'interpret', 'manipul', 'human', 'languag', '.']


In [8]:
lemmatizer = WordNetLemmatizer()
lemmatized = [lemmatizer.lemmatize(word) for word in filtered_tokens]
print(lemmatized)

['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'field', 'Artificial', 'Intelligence', '.', 'help', 'computer', 'understand', ',', 'interpret', 'manipulate', 'human', 'language', '.']


In [9]:
documents = [
    "I love machine learning",
    "Machine learning is amazing",
    "I love coding in Python"
]

In [10]:
cv = CountVectorizer()
X_tf = cv.fit_transform(documents)

print("Feature Names:", cv.get_feature_names_out())
print("TF Matrix:\n", X_tf.toarray())

Feature Names: ['amazing' 'coding' 'in' 'is' 'learning' 'love' 'machine' 'python']
TF Matrix:
 [[0 0 0 0 1 1 1 0]
 [1 0 0 1 1 0 1 0]
 [0 1 1 0 0 1 0 1]]


In [11]:
tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(documents)

print("Feature Names:", tfidf.get_feature_names_out())
print("TF-IDF Matrix:\n", X_tfidf.toarray())

Feature Names: ['amazing' 'coding' 'in' 'is' 'learning' 'love' 'machine' 'python']
TF-IDF Matrix:
 [[0.         0.         0.         0.         0.57735027 0.57735027
  0.57735027 0.        ]
 [0.5628291  0.         0.         0.5628291  0.42804604 0.
  0.42804604 0.        ]
 [0.         0.52863461 0.52863461 0.         0.         0.40204024
  0.         0.52863461]]
